baseurl = "/"        
metaDataFormat = "yaml"
title = "BlistImproved"
theme = "blist"

#baseurl = "https://blist.vercel.app"   the original theme site demo

#Paginate = 20
#PaginatePath = "/"
#summaryLength = 10

#[taxonomies]
#category = "categories"

#[permalinks]
#posts = ":section/:year/:month/:day/:title/"


# sectionPagesMenu = "main"



    [Site.params]
      introTitle = "Hey! I'm Katheryn Fox"
      introSubtitle = "26 y/o junior developer who enjoys social card games, blogging and painting"
      introPhoto = "/picture.jpg"









[params]




  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  # copyright = "Copyright © 2021 - Katheryn Fox · All rights reserved"

  favicon = "/favicon.svg"
  # favicon = "/images/favicon2.png"


  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-gray-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "I work on everything coding"
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  xing = "https://www.xing.com/profile/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"



[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true



[params.clients]
   enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""
    


#googleAnalytics = "" #UA-xxxxxxx google Analytics

# disableLanguages = ['fr', 'ja'] This can be useful when working on a new translation.

# rssLimit = 3 #max num of items in the RSS feeds

enableEmoji = true  # Enable https://www.webfx.com/tools/emoji-cheat-sheet/